# Generated by Django 2.2.6 on 2019-12-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191221_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(default='ii', max_length=100),
            preserve_default=False,
        ),
    ]
