# Generated by Django 2.2.6 on 2019-12-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191225_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
