# Generated by Django 2.2.8 on 2019-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191225_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о заявителе'),
        ),
    ]
