# Generated by Django 2.2.8 on 2019-12-30 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20191230_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя исполнителя/Название группы')),
                ('text', models.TextField(verbose_name='Содержание заявки')),
                ('format', models.CharField(choices=[('S', 'Сольное выступление'), ('G', 'Группа')], max_length=1, verbose_name='Формат')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий/Пожелания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Автор заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сцены')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Первый день'), (2, 'Второй день')], verbose_name='День выступления')),
                ('time', models.CharField(choices=[('D', 'День'), ('E', 'Вечер'), ('LE', 'Поздний вечер')], max_length=2, verbose_name='Время выступления')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(choices=[('YES', 'За'), ('NO', 'Против'), ('ABS', 'Воздержался')], max_length=3, verbose_name='Решение цензора')),
                ('censor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Цензор')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Решение цензора',
                'verbose_name_plural': 'Решения цензоров',
            },
        ),
        migrations.CreateModel(
            name='SceneSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество выступлений в слоте')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Request', verbose_name='Заявка')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Scene', verbose_name='Сцена')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.TimeSlot', verbose_name='Временной слот')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Scene', verbose_name='Желаемая сцена'),
        ),
    ]
