# Generated by Django 2.2.8 on 2019-12-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_remove_sceneslot_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='scene_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='festival.SceneSlot', verbose_name='Сцена и временной слот'),
        ),
    ]
